### ISSUE TITLE
Use react-scripts (default with create react app)

### ISSUE THREAD

**Issue by RoeiRom** [y-golde/evenyesodAssignment#21]
https://github.com/y-golde/evenyesodAssignment/blob/6fb1794b02ae167685c0f6c6f8440a511461a6e9/package.json#L7

**Comment by y-golde** [comment]
fixed 57b7392ed0dce1f49e5a7dfd2a98c048dc9f8d3b , 
that line was there by accident - the dev option moved to server.js
