### ISSUE TITLE
Don’t use shallow use mount 

### ISSUE THREAD

**Issue by RoeiRom** [y-golde/evenyesodAssignment#22]
https://github.com/y-golde/evenyesodAssignment/blob/6fb1794b02ae167685c0f6c6f8440a511461a6e9/src/Tests/Pages/editUser.test.tsx#L27

**Comment by y-golde** [comment]
באופן כללי עברתי לmount בקובץ test החדש ( 2cf863bcfc920ae5f6d07f626ea2162ac875279c , לא גמור עדיין :\ ),  
אבל מה הרציונל? בעיקרון אני גם מייבא את הcomponents של MUI וגם את הcreateShallow שלהם כדי לבדוק את הרכיב TextField נניח (במקום לבדוק את הinput)

**Comment by RoeiRom** [comment]
כי mount מרנדר לך את הקומפוננטה ממש עד הסוף וshallow רק את השכבה הראשונה. לנו עברו טסטים בגלל זה למרות שהם לא היו אמורים לעבור נטו בגלל זה

**Comment by y-golde** [comment]
fixed b64e207525b3835ed171817f9aa01ab0d47e6270
tnx
