### ISSUE TITLE
If the function is only one line why a function

### ISSUE THREAD

**Issue by RoeiRom** [y-golde/evenyesodAssignment#25]
https://github.com/y-golde/evenyesodAssignment/blob/6fb1794b02ae167685c0f6c6f8440a511461a6e9/src/Components/navbar.tsx#L67

**Comment by y-golde** [comment]
readability I guess , it seems more natural to me to write
`if(somethingHappened) {
    redirectToLoginPage();
}` 
than
`if(somethingHappened) {
    location.href = "/login";
}`

**Comment by RoeiRom** [comment]
I think it is understandable, maybe you can make it a const that it’s name is login route

**Comment by y-golde** [comment]
cool , thank you -
fixed in 5def5d876af4c5cb3d07d6b79e65cbbf35d438a7
