### ISSUE TITLE
Env variables should be DISCRETE!!!!

### ISSUE THREAD

**Issue by RoeiRom** [y-golde/evenyesodAssignment#27]
https://github.com/y-golde/evenyesodAssignment/blob/6fb1794b02ae167685c0f6c6f8440a511461a6e9/server/env/prod/.env#L1

**Comment by sandymash** [comment]
same for all .env files in project

**Comment by y-golde** [comment]
fixed 
a7aa717b3660a0f10f492e9373583f800763deee
