### ISSUE TITLE
You can do the connection string in env variable

### ISSUE THREAD

**Issue by RoeiRom** [y-golde/evenyesodAssignment#29]
https://github.com/y-golde/evenyesodAssignment/blob/6fb1794b02ae167685c0f6c6f8440a511461a6e9/server/Database/db_url.ts#L1

For example, the connection string of a DB with ssl connection is different in non ssl connection

**Comment by y-golde** [comment]
tnx haven't noticed that :) ( I used pg.pool instead of a url so I needed separate variables)

fixed in e0bc3d790dd684952ca0bb54db8611db153cff5f

**Comment by RoeiRom** [comment]
You can use a connection string in PG pool and it will do a connection pool to the DB
