### ISSUE TITLE
No need to compare to specific bool value implicitly

### ISSUE THREAD

**Issue by sandymash** [y-golde/evenyesodAssignment#30]
https://github.com/y-golde/evenyesodAssignment/blob/6fb1794b02ae167685c0f6c6f8440a511461a6e9/src/App.tsx#L52-L53

----

isUserAuthenticated, isSignedIn are boolean values 
they can be checked for truthiness by just if(isUserAuthenticated)
or falseness by if(!isSignedIn)

**Comment by y-golde** [comment]
correct, hadn't noticed that ,thank you
fixed in 662640a4ca7b9833707f0287ec97b5781449a987
