### ISSUE TITLE
add error handling to response in server

### ISSUE THREAD

**Issue by sandymash** [y-golde/evenyesodAssignment#31]
https://github.com/y-golde/evenyesodAssignment/blob/6fb1794b02ae167685c0f6c6f8440a511461a6e9/server/Functions/beers.ts#L8-L10

handle errors in response as well, preferably with corresponding status + message;
(and then catch said errors on the frontend)

**Comment by y-golde** [comment]
tnx , fixed in f4a746be70396c44578dbc8e1b8ceb1a315ee687
