### ISSUE TITLE
There are a few functions that could be variables

### ISSUE THREAD

**Issue by sandymash** [y-golde/evenyesodAssignment#32]
https://github.com/y-golde/evenyesodAssignment/blob/6fb1794b02ae167685c0f6c6f8440a511461a6e9/src/Pages/login.tsx#L29-L31

https://github.com/y-golde/evenyesodAssignment/blob/6fb1794b02ae167685c0f6c6f8440a511461a6e9/src/App.tsx#L81-L83

functions that dont do any action or calculation (just return value) such as these can be a variable

**Comment by y-golde** [comment]
yea but I think that 
`if(userIsNotLoggedIn())`
is more readable than 
`if(!isSignedIn)`

how would you make those functions constants?

**Comment by sandymash** [comment]
I personally think `if(!isSignedIn)` is more readable, since it takes less time to read and you dont have to refer to a function to see how that value is retrieved
but even if you want to keep the name as it is, the function could be rewritten to be - 
`const userIsNotLoggedIn = isSignedIn === false;` or rather `const userIsNotLoggedIn = !isSignedIn;`

**Comment by y-golde** [comment]
thank you,
fixed in d2c3c734cd735415faa310755a562f18416b6c5e & 758525506945e89aa0228b62b72f8545f3b2365d
