### ISSUE TITLE
single quote all over the project

### ISSUE THREAD

**Issue by ItayBenMoshe** [y-golde/evenyesodAssignment#42]
https://github.com/y-golde/evenyesodAssignment/blob/e68c4bef6ad253d3a6422ee7c7861782e0ece42d/src/App.tsx#L3

**Comment by y-golde** [comment]
its double quote because my prettier is set to format to double quote , why single quote?

**Comment by ItayBenMoshe** [comment]
one of our standards in the project

**Comment by y-golde** [comment]
fixed 46ab61cb9fddccb9243a460409e708aece53dfaa
