### ISSUE TITLE
imports order 

### ISSUE THREAD

**Issue by ItayBenMoshe** [y-golde/evenyesodAssignment#44]
https://github.com/y-golde/evenyesodAssignment/blob/e68c4bef6ad253d3a6422ee7c7861782e0ece42d/src/App.tsx#L6

I think i already told you about it.
You should have 3 sections - it should be in the third section

**Comment by y-golde** [comment]
I don't have any commons/utils throughout my project 
so I don't have anything to put in the middle section

**Comment by ItayBenMoshe** [comment]
./ should be in the third section

**Comment by y-golde** [comment]
yea but i dont have a second section :0

**Comment by ItayBenMoshe** [comment]
I know. make one

**Comment by y-golde** [comment]
added :) , f669fe485fab1eb21aae63895f4375163de73ea3
