### ISSUE TITLE
props

### ISSUE THREAD

**Issue by ItayBenMoshe** [y-golde/evenyesodAssignment#47]
https://github.com/y-golde/evenyesodAssignment/blob/e68c4bef6ad253d3a6422ee7c7861782e0ece42d/src/Pages/EditUser/editUserForm.tsx#L20

I didn't see you pass props to the component

**Comment by y-golde** [comment]
it was originally for testing (like the loaded prop), 
forgot to remove it :0
fixed 01a59a4ca9468dc3f22d19fb64fcbf762ab8c0ec
