### ISSUE TITLE
defaultValue

### ISSUE THREAD

**Issue by ItayBenMoshe** [y-golde/evenyesodAssignment#48]
https://github.com/y-golde/evenyesodAssignment/blob/e68c4bef6ad253d3a6422ee7c7861782e0ece42d/src/Pages/EditUser/editUserForm.tsx#L32

You can use defaultValue api from react-hook-form to initialize the value

**Comment by y-golde** [comment]
yea , originaly it was intended for testing , but got rid of it in 01a59a4ca9468dc3f22d19fb64fcbf762ab8c0ec , ill use defaultValue next time though :P
