### ISSUE TITLE
array type

### ISSUE THREAD

**Issue by ItayBenMoshe** [y-golde/evenyesodAssignment#49]
https://github.com/y-golde/evenyesodAssignment/blob/e68c4bef6ad253d3a6422ee7c7861782e0ece42d/src/Pages/EditUser/editUserForm.tsx#L36

You can type it Beer[] instead

**Comment by y-golde** [comment]
tnx fixed in ba406c950f95026e70f717384012cd7c8af202a0 I thought that there was a difference turns out there isn't <sup>[kinda](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#caveats)</sup>
