### ISSUE TITLE
both syntax

### ISSUE THREAD

**Issue by ItayBenMoshe** [y-golde/evenyesodAssignment#50]
https://github.com/y-golde/evenyesodAssignment/blob/e68c4bef6ad253d3a6422ee7c7861782e0ece42d/src/Pages/EditUser/editUserForm.tsx#L43

There is a reason you use both async and then and catch syntax?

**Comment by y-golde** [comment]
Beacuse I want to wait for all beers to load before I get the user's details (so I can cross between the users fav beer and all available beers

**Comment by ItayBenMoshe** [comment]
but you also have await in line 67

**Comment by y-golde** [comment]
Hi , Ive added the beer id to the query factor and removed async from the function here : f1510ff3b451f67d3d1b161b7eecd52dd5fb196a
tnx :)
