### ISSUE TITLE
then scope

### ISSUE THREAD

**Issue by ItayBenMoshe** [y-golde/evenyesodAssignment#52]
https://github.com/y-golde/evenyesodAssignment/blob/e68c4bef6ad253d3a6422ee7c7861782e0ece42d/src/Pages/EditUser/editUserForm.tsx#L56

set the beers inside the then scope - you don't need the condition

**Comment by y-golde** [comment]
fixed 01638d7e2b3704c513a7490022632ae4977f2d17
