### ISSUE TITLE
boolean type

### ISSUE THREAD

**Issue by ItayBenMoshe** [y-golde/evenyesodAssignment#53]
https://github.com/y-golde/evenyesodAssignment/blob/e68c4bef6ad253d3a6422ee7c7861782e0ece42d/src/Pages/EditUser/editUserForm.tsx#L38

boolean instead of Boolean - don't know if there is differnce (you can check if you want)

**Comment by y-golde** [comment]
6748bcc0e45498b548b2be805778feb9ef021309
fixed tnx
