### ISSUE TITLE
form context

### ISSUE THREAD

**Issue by ItayBenMoshe** [y-golde/evenyesodAssignment#55]
https://github.com/y-golde/evenyesodAssignment/blob/e68c4bef6ad253d3a6422ee7c7861782e0ece42d/src/Pages/EditUser/editUserForm.tsx#L121

You can wrap form with FormProvider - gives you the ability to avoid from passing props related to react-hook-form
just use useFormContext inside FirstnameInput for example.
you can read about it

**Comment by y-golde** [comment]
yea I know , unfortunately FormProvider causes the element tree to re-render whenever react hook form [triggers a state update ](https://react-hook-form.com/advanced-usage#FormProviderPerformance)

**Comment by y-golde** [comment]
Hi , I've added the FormProvider (baed3217cafb89f510ce2c40f7992530d3e477e1) and found out this : 
first vie added the following line to ```validatedTextField.jsx``` 
![image](https://user-images.githubusercontent.com/68457306/101749189-2306e980-3ad6-11eb-987b-1a5f8f860ad3.png)
then I wrote something into "lastname" field and received the following log:
![image](https://user-images.githubusercontent.com/68457306/101749357-50ec2e00-3ad6-11eb-94bf-7af8788eab11.png)
meaning an input to a single text field **re-rendered everything under ```<FormProvider>```** as you've suggested yesterday
