### ISSUE TITLE
custom hook

### ISSUE THREAD

**Issue by ItayBenMoshe** [y-golde/evenyesodAssignment#56]
https://github.com/y-golde/evenyesodAssignment/blob/e68c4bef6ad253d3a6422ee7c7861782e0ece42d/src/Pages/EditUser/editUserForm.tsx#L43

You can write your own custom hook and move functions there.
you should isolate between functionality and ui

**Comment by y-golde** [comment]
thank you , fixed in 361932ec124d6b7c11daf9139e62a6bb37029e4f
