### ISSUE TITLE
generic components

### ISSUE THREAD

**Issue by ItayBenMoshe** [y-golde/evenyesodAssignment#57]
https://github.com/y-golde/evenyesodAssignment/blob/e68c4bef6ad253d3a6422ee7c7861782e0ece42d/src/Pages/EditUser/editUserForm.tsx#L127

both FirstnameInput and LastnameInput components look the same - you can write it more generic

**Comment by y-golde** [comment]
fixed , f669fe485fab1eb21aae63895f4375163de73ea3

changed the inputs to a generic input type in commons
