### ISSUE TITLE
Redux thunk

### ISSUE THREAD

**Issue by NaamanTsur** [y-golde/evenyesodAssignment#59]
Currently you handle perform your axios request in your react components. With redux you can handle those requests using [the Thunk library](https://github.com/reduxjs/redux-thunk). [More explanation here as well](https://redux.js.org/tutorials/essentials/part-5-async-logic#thunks-and-async-logic)

**Comment by y-golde** [comment]
see 19625586b6c2c723945fcba72966141c88a3b278 , is my usage here ok? is there a cleaner way to do is? I feel like moving the async action to the action.ts is not clean :/ and keeping it in useFoods is not clean either

**Comment by NaamanTsur** [comment]
In general writing the async action in action.ts is fine considering that it's still an action, only an async one. If you want to dive deeper into redux architecture patterns [re-ducks](https://github.com/alexnm/re-ducks) is a great place to start.

**Comment by NaamanTsur** [comment]
Writing the async action in the useFoods hook is not a good idea because defining the async action is not useFood's responsibility.

**Comment by y-golde** [comment]
Thank you! , moved the whole logic to the action , looks much cleaner now (i hope)
1fe515e33a514659a01c43a708b38db667c03a89
